server:
  port: 8762

spring:
  application:
    name: de.youthclubstage.backend:central-organisation-service
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    redis.clients: ERROR
    org.springframework.data: INFO

jwt:
  alias: jwtkey
  pass: z7hF2erPZeGqI9bp
  expirationMinutes: 2
